export const testData: Array<string> = [
    'MMMSXXMASM',
    'MSAMXMSMSA',
    'AMXSXMAAMM',
    'MSAMASMSMX',
    'XMASAMXAMM',
    'XXAMMXXAMA',
    'SMSMSASXSS',
    'SAXAMASAAA',
    'MAMMMXMMMM',
    'MXMXAXMASX',
]

export const minData: Array<string> = [
    '..X...',
    '.SAMX.',
    '.A..A.',
    'XMAS.S',
    '.X....',
]

export const fullData: Array<string> = [
    'MSSMMSXSMSMSXMXXXMSMSSMSAMXAXASXSASMSMXMXMMAMSMMMSMSXSAMXSSXMASMMMXXMASXMSXMSSXXXAMMXMXSMSAMAAASAMXMMSSSXXSMMXXXSMXSXMXMMXXMASMMMMSXXMAXXMAS',
    'XAAAAAXMASMSASXMAMAAMXAAMSSXSAMASASAAAXSAMXAMAAASAASAMMSMMMAXAXAMSMMAAAAAXASXAASXSSMAMAMXMASXMMAASASXMAMAMMAMSMMMMAAAMMSMXSAMXSAMASMSMSSMSSM',
    'MMSMMMSMAMAMAMSAMXMSMMXMAAXAMAMAMMMXMSMSAMSASMSMSMMMAMAAMAMSMMSXMAAMMSSMMSXMMMMAAAXMAMAMMSXMAXXXXSASXMASAASAMXMAAMSSXMXAAAMASAMXMXSAAAAXAXXS',
    'AXXXSAMMAMAMMMSXMASAMXMXMMMXXAMXSXAXXAAMAMSMMAAXSXXXXMSSSSSXAASMSMSMAAXAASAMXSSMMMXMXXASAMAMAMSSMMXMASAXMXXXSASMSXAAMSSMSMSAMASXSMSXMSMMSMMM',
    'SSMAMASXMSASXASASMSAXXAXXSXXSAXAXMSXMMSMAASASXMMSAMXAXMMAMXMMASAAAAMMSSMMSAXAXMXXAMSSSXMXXAMAMXAAXMSAMMSMMSMMXSAXMMSMAAAAXMASAMMMASAMXXSMAAM',
    'XAMMMAMXAXAXMASAMMSXMMMSAMXMAMSMSXMASAXMSXSMMASXMAMSAMXMSMXAMSMMMSMSMAXMASAMSSMMMMSAAXMAMSASXSSSMMAMXSAAASAMSAMXMAMAMAMXMMSXMASAMSMMMMMXMMMM',
    'SSMMMASMXMMMXAMXMXMASAAMMXXSAMAAMASAMAMXXAMASAMMMSMAAAXSAMXAMAAAMXMAMXMMASMAXAMXAXMMMMMAMMAMXMAAXMMSAMMMSMAXSASXAMSASXSSMXXXSAMASAMASASMSMSA',
    'AXAAMMXMXMAAMMSMMASMMMXSXXMAXSMAMAMAMASMMMMAMXSAXAMAMSMSMMXXXMSMSXSXSMSSMMMMSAMMSMSAMAMMXSSMMMSMMMAMASAXXMSMSAMMAMMMMMMAMSMMMMSMMASASMSAAAAS',
    'ASXMSMASMSMSMSAAXAMAXSAMXMAMASXSMSSXMAAXAAMASXSMSXSXMAMMXMMSMXMMXMMASAAAMASASAMXAAMXSAXSAMXAXMASAMASXMXXSAMXMAMMXXSMSAMMMAAAXMAXSXMASXMMMXMA',
    'MXMAMMMSAXMAXSSSMSSSMXMAXSMXMMAXAXAMMSSSSMSMSXMAXMXAMXXMASAAMAMAAAMAMMSMMAMXSAMMMSMASAMMMMMMMSASMSASAMXXMAMASMXMMXSASMMXMMMMMSSMXAAASAMXSSMM',
    'ASMMSSMMMMMSXMAMAXAMMMMSMMASXMAMXMXXXAAMAMMAXAMSMASMSSXSAMSMXAMMSSMSSXXAMXXASMMMAAMXMMMMMXMAMMMMAMXXAMAXMAMMMMAAMSMAMSMSMSMSMAXMASMASAMXMAMX',
    'MXSAAMXSMAAMAMXMXMAMXAAAASAMAMAMMAMXMMSMMAXXAMXAXXMAAAAMXMAXMSSXAAAMAAMSSSMASXAMSSSMAASAMXSASAMXMXAXSMSMSASXMSSSXMMSMMMAAAAAMXMXAXMMMMMMSMMM',
    'XAMMSMASMMSSMMMMXMMMSMSSXMMSXSXMXXAXSAMXXMSAMXMMSSMMMMMSXMASAAAMSMMMMSXAAAMXMXSXMXAMSMSASAMMSMSXXMSXMAXAMASAMXAMASAAMASMMMSMSMSAXAXSMSSMMXXS',
    'MSMMXMXSAMAMXAAMAMMAMMMMAMASASAMSSSMMMSAMXMMXAAXAASAMAXMXAAMMSSMXMASXMMMSMMAMAMXSMMMMXSMMMSMXMMMXAMAMMMSMMMAXMAXAMMXSASXXXXMAAAMMSAMXAAAXSAM',
    'XMASXMASAMMXSSXSASMASAMXAMMMAMAMAAXAMASAMXAMXXMMSMMMASAMXSXSXXAMXSMMMMAXMASXSSMMSAXAXASMSXAXXAAAMSMAMAAXAXMSMMSMMXAMMASMMSAMMSMXAMAAMSSMMMAX',
    'MSAMAMASAMXMMAMXMAMASASXXSAMXXXMMSMSMXXAMSSMSSMXMAASMXAMXXAMXSAMAMXAASXMSAMMAAXASXMASMSASXSSXSAMSAXSSSMSAMSMSAAMAMSXMAMMAXXMXAXMAMMXAMXMXSMM',
    'XMAXXMASAMMAMAMAXAAMMAMAASXSMSSMAMMXMASMMXXAASMAMXMMAMMMMMXMAXAMMMSSMMAMMMMMSMMMSAMAMXMAMAMAMXAXXAMXAMAXMXAAMSSMAXAAMMSMSSMXXMSSSMMASXMXAMAS',
    'SSSMSMASAMSASMSMMMSXMXMMXMXAMAAMSMSAMXXMASMMMSMASAMMXMAMAXXSMSMMAAMMMSAMXMAMAMSXSXMMMAMAMXMXMMMMSMSMAMMMMSMSXXMXXSSXMAAAMXMASXAAAAMAMAXMXSAM',
    'MAAAAMXSMMAASXAXMAAMSMSMSMAMMMSMMAXXXSAMXMMAAXXASASAXSASXMMMAAMMMMSAASAMXSXSAXSASXSAXAMASASASXAAAMAXSMXXMXXMMSMMMMXAMSSSXAMASMMSMMMSMXMMAMAS',
    'MSMMMXAMMSMMMMMSMAMMAAAXXXSMSAAAMMMSMSXXSXSMSSMXSAMAMMASAAAMMMSXAMMMMSAMAMMSXMMAMASMSXSMSASXMXMSSSMAXAMXXMAMAXSAAMSMMAMXMXMASAMAMAAXSMAMXSAM',
    'XXAXXMASAXAAAASAMMSSMSMSMXMAXSMMMSASAMXASAMAMXMXMXMXMMXMMSSSSMXMXSAAXSXMMSAMMMMAMXMAAASXMAMAAXXXAXXXSAMMXMXSSMSXXMAAMXSASXMASAMMSMXXAMXMASAS',
    'MSMSMMMMASXMSMSASAMXAAAXAMMMMXMMAMASAXMASMMAMAMMMXAMXXMMXMAAXMASMSXSMSAMAMMXAAMXXAMMMMXAMXMXMXMSMMSMAAMXXXMAAAXASMMXMMMXXAMAXAMXSAMSSMSSMSAA',
    'MAMAAAXXMXMAXAMMMXSMSMSMMMASMSAMXXMMMXMASXSXMASASASASXAMAMMMMSXXAMAMASAMASMSSSSMXXSMSSSSMSMAMAMAXMAAXMMSMMAMMMMXSAMSSMMSSSMSSMMAMAMAMMXAAMXM',
    'SASMSMSMMAMASASMSMMAMXMXMMAMASXMMSSMSAMXSAMASASMSAXAMAXSASXSMMSMSMAMXMAMASXAAAAASMMMAAXXAMMAMAXASMMSMXXXXAXXMXSAMXMAAAXAAXAMAAMXSAMMSMSMMMAM',
    'SAXXAAAXMXMASAMXAAMAMASAMMSMMMAMAAAMAXAMMAMAMMSXMXMAMSMSAMMXAASMAXAXSSSMXSMMSMMMXAAMMSMMMMSMMMMMXAMMASXMSXSAMXMASMMSSMMMSMSSXMAMAMSXAAXAAMAS',
    'MMMSMSMSXAXXMAMMXMMASMMASAAAASAMMSSMMMSXSMMMSAMXMMSMMMAMAMMXMMSSMSXSMAAAXMAXMXMXSXMMAAAAMMAMXMASXSMMMAAAAAXAMXSMMMMAAAXXAXXAMSASASMXMSMSMSMS',
    'XSAMAMAAXMMXMSMXAXSAXAMAMMXMMXASAMAAXAXAMMAXMAMAXAAAAMAMXSAASAXAXAMSMSMMMSSMMASXSAAMMSMMXSASASMSAXAMSSMMMSXMMXXSAMMSSMMMSSSMAXAMXMXAXMXXXAXX',
    'MMASAMAMXSAMXAASMMMMSSMSXMMSSXMMMMMMMMSAASXSSSXMSSMSMSXSAMMSMASXMXMSAAAMAMMMSAMAMSMMAXAMXSASMSAMAMAMAAAAAXASMMMMXSAAAAXAMXAXSMMMSXSMMXASMSSM',
    'MSMMASXXMSSSMMMMAAXAAAXMAMAMAASMSSXMSXSMMXAAAMXMAMXXAMXMXSSXMXMAMMASXMXMXSAAMAMXMMXMASAMMMMMMMXMXMAMSSMMAMAMMAAAXMMMSMMSSXMAXASXAASXMMXAMAMA',
    'MAMXAMXSAMAXXXMSSMMMSMMSMMAMSMMAXMASXAXASMMMMMSMASAMAMASXMMASMSSMMASMMSMMMMSSXMSXSAMXSMMAXXAAMMAAMAMXMMMMMSMMSMSSSMXAMXMAMXASXSAMXMAXXXXMAMM',
    'SASXMMMMAMMMSMXMASXMAMMAMSSXMAMMMSXMMXMMAAMXXAMSMMMSSMMXMAMXMAAXXMAMAXAAAXMAXAAMXMASXMASXMSSSMASMSMSAMXASAXAMXAMMAMXSAMXXMMXXAXXXAXXMASXMMSX',
    'SAMXXAASAMAAAAMSXMXMAXXAMAXAMAMAAMASASMXSMMMMMXAXMMAMASMSAMXMMMMSMSMSMSXMSMASMMMASAMXSAMXXAAAMMMAAXMMMSASXMASMAMMXMAMAMAAXXASMXSSSMXSXMAASMM',
    'MAMASMMSMSMSXSAMXMXMXSSMMSSMSSSMSSXMASMXASXXAXSXSXMXSAMXSASASXAXAAMMXXMASAMXMXAMXSASXMASMMXSXMASXMXAAXMMMMSMMXSMMXMAXAMSSXMMMXAMAMMXMAMSMMAM',
    'XMMMAMAXMAMMAAAXAASXXMASAAAXMMAMXMXMXMMMMAXMMMSMMXXXMAMASXSASMMXMMMXSAMXSAMASMXSASMMAASMMAXMAXXSASXSMXSAAMMMSMMAMMSSSMXAMAXXAMMMAMXAXMMAMMSM',
    'XXAMAMXMXSAMXMMSXXAMMSAMMSMSXSAMAMMSAMXSXMSMSASAXAAMSSMMXAMXMASASASMSMMAMMMASXXAMXMSXMASXSAMXSAMAMMAXAMMMSAASASAMXAASMMASXMMAMAMSSSSSSMMSAMX',
    'ASXSMSMMMXAXXAMAXSMAAMXSXMMSASXSMSASASASAXMAMASMMMAAAAAMSMMXMMSASASAMMMSMMMMMXAMXSMXMASMXXSXSAMMMXSMMSXSAMMXSASXSMMSMMMMAMXAMMMMMAAXAAXAMASA',
    'MMAMXAAMASMXSAMAXAXSMMAMXAAMAMAAAMMSAMXSASMXMAMAMXAXXSMMAMMMSAXAMAMMSXAMXSASMMXMASAAAMXMASMXSMXAXMMXAXXSAMXAMAMXXXXAXASXMAMMXASAMMMMXMMXSAMM',
    'XXSSSSSMAAAASAMSAMXAXMASMMMSSMMMAMMXAMXMASAMXXSSMSMSMAMMXSAAMXSXMXMAMMMMAMASMXSXMXSMMMAXMAMAMXSMMAMAMAMXMXMMMXMXMASXMMMXXSSMSAXAMSAAAXXXMXSX',
    'XXXAAAXMSMMMSXMXMAXXMSAXMAAAAXAMASXSXMXMXMMAXXMAXSAAMXMAASMSXMAXXSMMSASMAXSMMASAMAMMXSMXXAMASMSAXSASMSMMMAAAAAMASAXSAMXSXMAXXASMMXMSSSXXMASA',
    'MSMMMMXMAXMAXAXMMSSSMMSMSAMSMMASAXXSAMXXAAXSMSAMXMSMSXMMXSXMASMMMSAMSAMMMMMAMMSAMSXSXMAMXASXXAMXMMAMAMAASMSMSXSAMAMAXSAMAMMMMMAMXMXXAMXAMAMM',
    'AXAXXXXMMSMMXSMXAAMAAAAXXMXMASXMMSMXAMAXSSMAXMASMMMXSXMMXMASAMXAAMAMMSMASAMAMXSAMAAXMSAMMMMMMSMMMMAMMSSMSXXMAAMMMSMMXMASAMAXSAXAMAXMAMMMMASA',
    'SMXMMMMAAMAAAXAMMSSSMMSSXMAMMMAXAAAXSMSMMAMAXMASMASAMAXAASAMASMMXSXMAXMXMAXAMXSXMMSMAMXSASASMXAXXSXMXMMASMSMMSMMAMAMMSAMXSSSMXMXASMMAMMSAXAA',
    'XAAMXAXMMSMMMSASXAAMXMMMMXAXASMMSMSMMAMXSAMXMMMSMAMASAMMMMXSXMXSASAMAMXAXXMSSMMASAMMAMXSAMASASXMASMSSSMMMMSASMXSASAMASMSXAMXMASXSMMSXSAMXSSM',
    'MSSSSXMAXMXAASAMMSSMMSAASXMMASMAAAAMMSMXMASMXAXMMAMXMMSAAXXAXMXMASASAMXSSXXMAAMXMAXSASXMSMAMMMXSMSAXMAMXAAMXMAASXSASXXAXXXAAXSAMXAAMMMASAAXS',
    'XXAXAXSXMXMXXMAMAMAAXMMMSASMAMMSMMSXAXXAXAMASMSXSSSMXAXMSMMAMXAMAMXMASAAAMMSSMMAMMMMASMAXMAMAAASAMXSAMMSMSMAMMMXASAMXMMMMMSMSMSASMMSMSAMXMSA',
    'XSMMMMSMAXAMXSMMSSSMMXSXMAMMMMAXXAXMMSSMMSXXAMMMXXAAMSSMAMMAMXMSAXXSAMMSMSAMXASASXSMAMMSMSSSMMSMAMAMXAMXAAXXMMSMMMAMMXAAAAAMAAXMMAMAAMSMSXAM',
    'MXXAMASXMMXSAMAAAMAASAXAMAMASMSSMSXAAAAXAXMMAASMSMMMMAAXASMMMAMAMAXMASXMXMMSMMMASAAXSXXAAAAAXXXXAMXAMXMMSMMXSAXAXMASMSMSMSSSMSMMSAMMSMAXMMMX',
    'AMXXSASAMAXMASMMSSMSMASMSASASAMXAAMMMSMMASASXMAXMASAMMSMXSMMSMSASMMSAMXSSSMSASXXMXAMXAAMXMSMMMMSXMMMSMAXMAMXMXSAMSASAAXXMAXAMXAXMAMAMMMSMAXS',
    'SAMXMXSAMASXMMASXMXAMXMAAASMMMMMMMXSXMASMSAMMSMXXAMMSXAXAXAXAMMAMXXMASXXXAASAMMXSXMXXSMSXMXMXAAMASAAAXMMSMMMXAMAXMSMXMSMASXMMAXSSSMAMAAAASAS',
    'XXXXSMSXMASAMXXMAMSMSAMXMMMMAAXAXXASASAMMXMAMMXSMXSAMXSMMSMMMASAMXSSMMMMMMMMAMSXMASMXMAXAMASMSMSAMMSMSXAXXAMMMSAMXAXASXXAXAMMSAMAXASMMSSSMAS',
    'XXSAMXSXMASAMAAMAMSASMSMSMASMSSSXMMMAMMMMMMXMXAMXAMAMSMAAAXAMASASAAXAAAAXXXSAMMAMAMXAXXSMMASAMAMXSXMXMMSMXXMAXXAMXSMMSAMXMAMAMAMXMAMAMXXXMAM',
    'XAMXXMSASASAMXXMAXMAMASAASXMXMXAASXMXMAAMAAAMMSSSXSAMXASMMSSMXSAMXSSSSSSSMASMSMXMMXSSSMMXMASMMMMXMASAXAAAMSSMSMSMAXXSXMASXXMXSAMAAXSSMAXMMAS',
    'MXMMAAMAMAMAXSASXSMMMAMSMSMMAMMSMMAMSMSSSMSXSAXAAMXAAAXMAMAXMAMXSAMXMAMAAMAMMAMMMSAAMAAAAMXSXSAMAMAXXMMMXMAAXAAXMAMSMAMXMASAASMSSSXMAMXMMASM',
    'SAXMASMMMMSAMSAMXAAXMMMMMMASMXAXMSAMSAMAAMAMMXMXMAXXMXSSXMAXMAXMSAMXMAMSMMSMMAXAAMMMMSMMSSMMASMSSSSXSAMSSMSXMMSMMXSXSAMMMAMMMMXAMXXAAXMSSMMX',
    'SMASAMXXAXMAMMXMSSMMSSMAAMMMSMAXMMMMXAMSMMAXXMAMXSAXXXAMMMSMSMSASAMXSAMAXAXMSMMMMSXXMXXXAAAMAMXAMAMAMXMXAAAMSMMXMXMAMXMXMASMMMMMMMMSSSMAAASX',
    'MAMSAXSMMMXXMAMXAMXAXASMMMSAMMMMSSMXSXMXXSMMSASXAMMMSAMXAAAXAAXMSSMMSSSMMMXAAAASXSMSMMAAASMMMXMMMAMSMSMSMMMAXAXASXMSMSMSAASXAAAAAAAAAXMAMMAS',
    'XAMXAMXMMXSAMMMMMSMMXMMSAMMAMSXMAAMAMAMXMSAXASMMMSAAASXSMSXMMXMXMASAMAMXASXSMSMSAXXAAMASXMMXMAXMMSMMAMXMXXXSSXSMMXAAAAAAMMMXMSSXMMMXMAMSSSXS',
    'SMSXSMSXAAXXMAAMXMASASAMXMMAMMAMXXMXSAMAMMAMMAXAASMMXXXMAAXAXAXASMMMSAMMMXAMAMAMAMSSSMMMMSSMSXSAAMAMXMSMMSMAAASXMMAMSMSMXMASXAXASMSSXSXAAMAM',
    'SAAAAAXMMXSSSSSSMSAMXMASAMMSMSAMSMSMMAXAMXAAXMXMMXAMSMXMXMASXXSASXAXMASASMAMAMSMSMAAMXAAAXAAAAXMMMAMXMAAAXMMMMMAMAXXMXAXXMASMSMMMAASAAXMXMAM',
    'SMMSMSMXSXAMAMAMAXASXMAMASAAXSMSAAAASXSSSSMSSMSXMMSMAMSXMMMAAXMAMXMSMXXASAAMASXAMMMMSMSMSSMMMSMSMMMMXSSSMSAXMASAMSAMXSASMMMXAMAXMMMMMMMSASAS',
    'SAXMAXMAMMMMAMXMXMXAAMXSAMMSMXSXMSMXMMAAAMAAAASMMAMSMXMAAXXMMMMAMAMAMAMSMXASXSMAMAAAAXMAMAXMXMXMAASMMMAAAXMMMASMSMMMXXMAMAASMSSMSAAAAAASASMS',
    'XMMMAMMASAXSMSMSSSMSAMAMAXSAMXMMXAXXXMMMMMMMSMMAMAMAXAMSMMMMAASASASAMMXXASXSASMXSMMMSXSXSMMMAXXMSMXAMXSMMMXAMMMMAAASMSMASMMXAAMASXSSSMMSAXAM',
    'MSXMASMXSXXSAAAMAMXAAMXSAMAAMMAASMSMAMXMSMXMMASMMSSSMSMXASMSSXSASMSMXMAMXMAMAXMMSXMXMXSAMXAMXSAMXXSSMAMXXAMMSSXMMSMMAASASXSMAMMXMAMAAMAMAMSM',
    'XSAMASAXMASMSMSMAMXMMMAXMASMMMMAMAAAAMXXMMAAMAMAAAAAAMAXAMAAMAMXSMMASMASAMXMXMSASMXAMAMAMSMSAXXMAXAAMXMXSMMSAMMSMXXMSMMMSASASMXMMXMSMMXXAAAX',
    'MMSMAXMAXSXMASAMASMSSMMMSAMXXMMSMSMSMSXAASMMSASMMSSMSMAMSMMMSXMAXAMAMMXSASASAAMASAMXSASAMAXMXMSSMSSSMASMAASMAMAAMXMMMASAMXSAMXXAMXAXXSSSSSMS',
    'SXMMSSXSMASMXSXSMSASXAMAMAMMSXAXAMXMAXXMMSAXMAMMAMXAXMAMAASAMASMSSMMSSXMMSASMSMSMXAMSXXMXSSMSXMAXMAXMASMMXMSAMSAXXMAMAMASXSAMXASXMXMAMAAAAXA',
    'AAXAMXAXAXMSAMXSAMXMAMMASXMAMMMMMSAMXMASAMMMMAMMMSSSMSXSSSMASAMMAMAAXXASXMXMAMMXMSSXMMSSXAAAMXSSMMMMMMSXMAMXMAMAMSXMMASAMMSAMSMMXASMSMMMMMSS',
    'MSMMMMMMMMSXSXAMMMSMSMSXSMMSSSMAMXAMMMXMAMXASAMXSAXAAXMXMAMAMXXMASMMXSMMAAXMXMASMAMAASAMMMMMXAMAAMXAXMXAMSXSSSMAMMAMSMMASAMAMAAXXMSAAMAXAAXX',
    'XMAMAMMAXSXAAMMSMAAAAASASAXAAXMASXSMAAAXXMSXSMSMMXSMMMAXMAMXSXMXMSXSXAAMAMMMAMSMMASXMMASMSSSMASAMMSMXMSMMAMXAASMMMAMAASAMXSSSSSMMXMXMAMMMMMM',
    'XMXMAMXMSMMMMMXAMMMMMSMAMSMMSMMXSAMXXSASXMMASXAAAMXMSSSMXSSMMXSAXMAMXSSMMXAXXMAASAXAXMAMAAAAMAMASXXAAXAMXMAMMMAXASASMXMMSAXAXMAXSAMMXSSXSASM',
    'MSMXMSMMAASMASMSMSSMMMMXMAMSAXMAMMMXXAAXAAMMMXXSMXMAMAAXAXAAAAMAMMAMAAMAMSSMMSMMMMSMSMSSMSMMMMSXMXMSMXASMXSAXXMSXMASMMMSMMSSSSSMMXSAAMAXSASX',
    'MASAAAXSMSMMASMAMAASASMMSSXSAMMAMXMXMASXSMMMMSMMMAXXMXMMMSSMMMSAXSAMMMSAMAXAAAMSMXAAAAMSAMXXXXAMXAXAMMSMMXMASXXSAMXMAXXAAMSAAAAXXAMMSSMAMAMA',
    'SASMSMMXXXAMAXMAMXSMMMAMAMMMAMSASAXSMMMAMASAAAAAMMSMMSXSXAMAXXAMXSASXASXSAMMMMSAAMMMMSMMMMSMSMSSSMSASMMAASMMMMAXMMMXMMSSXMMMMMMMMXMAXAXSMSMS',
    'MASXXXSSXSAMSSSXSXMMXSXMASXMSMSASXMSAMMXMASMSSSMSAMXAMMMMMSAMAMSXMASMXMAXMXSAXSMSXSAMXAXMASMXAAAMXMXMASXMXSAAMSMSAMAAAAAASXSMXAAXMASXMMXAXAX',
    'SXSASAAXASAMXAAASXMAMAMXXAXAMAMMMAMXAMSAMASAAMMMMMMMMMAMSMMASMXSAMAMMAMXMAXMAMXXMASAMSSMMASXMMMMSAMAMMMXMASXMSAASASXSMMSMSASAXSXSXMMAMMMMMMM',
    'MAMAMSMMMMASMAMMMAMMSAMSSSMXMAMSSXMSSMMXSAMXMAAAASXSMSMSAAXXAXAMAMMMSASAAXMMMAMAMAMAMAAAMASAAXXASASASXSAMMSXMMMXMAMAAAAXXMAMMMMAMXMSAMAAAAXX',
    'MXMAMAXAASMMAXMASXMXMAMAAMAXXAMXXAMAXAXMMMSAXSXSMMAAAAMSXSMSAMXSSMMMSASXSMSXMAAAMASXMXSXMXSMSSMMMXXASXXAXASAXMSSMSMSSMMSAMXMXAMAMMAMASMSXXSA',
    'AAMAXASMXXAXSXSASAMSSXMMMMMMSMSMSSMMSSSXAMXMAXAXXMSMMMMXAXAMMMMMAASAMXMMAMAASMMSXMXMSXMASXXMAXAMMSMMMMSSMASAMXSAAXAXAMXXMXSSMXSAAXMSMMAMMSMX',
    'SSSSXMMMXSMMMAMMSAMMSXAAMAAMAAAXXAAAAXAMAMAXAMMMMXMAMXMMMMSAMXAMMMMAMAMXAMXXXMAMXMMXSAMXSAMMSMSMASAMXAAAMAMXXMXMMMXMMSMMXAMAMXMMXAMAMXAMMMAM',
    'AAAAXSSMMAXAXXXXXXMAXMSMSSMSMSMSXXMMSMMAASXSASAAAAXAMAXAAMAXMSSSXXSSMSSSMSSSMMAMASAMXAMAXMMAXAMMXSSMMMMMMASXMMMSAMXXXXASMMMSAXXAASXMSSMSAMXM',
    'MMMMMXAAXXXASAMXSSSSMMXMXMAXXAMXXASXXXXSASXXASMMMSSSSSSSSSXMASAAXMAXAXAAAAAAAMMMAMXXXSMSMXMASASXMXASXMMXSASMAAAXASXMASMMSAAMSAMMXMAXXMASASMS',
    'XAXXXSSMMMXXMAAASAAAAAXSAMXMSMMXAMXAXMXMASXMAMASAMXXXAAMAXMXXMMMMAAMMMSMMMSSMMXMSSMMSMAXXAMASXMMMSAMXSAXMASAMMMSAMXMASAAXMXSMXXMASXMMSXXASAX',
    'XAXSAXXMXXAASXMMMMMSMMMMASXMXXMXSAMXMSMMSMMAAXXMSSMMMMMMAMMMXXXSSMSMMAXAXXXMMSMMAAASAMAMSSMXXMXAMMAMAMAXMAMMSAMXASAMXXMMMXSXMSASXMSAMXMMMMMX',
    'AXAMAMXMAXXXMMXAAAXAAMASAMAMMASAMAMXXMAXAAMSXSAAXXAXMAXMMSAAXSMAMXXAMSSMMMSMAXAMMSMMAMMMAAMXMAMSSSXMXSXSMAXXMAXSSXMMSXAMSXMAXSASAMXMXAXAXAXM',
    'SMXSAAAMASMASASMSSSMXMAMAMSMSAMXSAMXMMSSSMMAAXMXMXMMSXSAASMSMSMAXXSAMAAAAAXMASMMMMMSSMMMMXSAMSAMAAXSXMXAMAMSMMMXXASASMSMAMSMMMAMMMXMSMSMSXSA',
    'XAXMAXXXAXXAMXMAAMAASMSXXSAMMXSAMMSXAAAMAMMXSSSXSSMAAMMMMSXAAXSSMMXAMSSSMMSMMXMAMMAAAAASXMSASASMMMAMAMXMMSMSAASASXMASAAAMMAAAMAXAXAXAXAXMAMX',
    'SSSSMSMMMSMMMAMMMMMXMAMAXSAMAXMASMSMMMXMAMXAMAXXMAMMMSAMXMMSSXXMASXSMXAMXASASMSMMMMMXSMSAMXMMMXXAMAXAMXXMXAMSMMASMMMMXMMXMAMXSASMXSSMSSSMAMX',
    'XAAXAAAAMAASXSMMAAXAMAMSMSMMMSMMSAMASASXXXMXSAAMSSMSASASAXXMMAXMXMAMXMXMMAMAMXAASXSMAMASAMAXAXMASXSSSSMAMMMMMXMXMXAXMASXMMSSMMMSAAMAMXMAMXMM',
    'MXMMSMSMSXSAAMSSSMSSXMXAAXXAXAXMMASMMASAMSXMMASXAXXMXSAMAXXASMSMXMXXXSXSMSMXMSMSAMAMAXASASXSMSAXMAXAAMMASAXAXAMMMSMSMXAAAAAAAAXMMMMAMXXSMSXA',
    'AAMAXXAXSXMMMMAXAAAMAASMSMSMSMSXSAMXMXMASMXMXAMMMSMMAMXXMMMMAAAMMSSMMMAAAAMXXXMAMAMMSSMMAMXAASMSMMMMSXSASASMSMMAMAXAAMMMMMSMMMAMSSSSMMXAAMSS',
    'MAMASMSSMAXXXMXSMMMMMMSXMAXMAMMMMMSAMAMMAMMMMMXXMSMASXMXAMXSMSMMAMAAAMSMMMSMMXSAMSXAAMAMMMXSASMMAXXXAAMAMASAAMSMSMSMSXXASMMMSXSXAAAXAXSMSMAM',
    'SMSMSAMAMAMMSSMMAXSAMXXAXSMSAMXMAMMMXAMXSXAAAAASMXMAMAMSXMASXMMMSSSMMXXAXXAAMAMASMMMMMAMAMAMAMAXXMXMMXMMMSMMMMAASXSXXXMASAMASAXSMSMMMMMAXMXM',
    'AAAAMXSAMASASAMAAASASXSMMMXMMMMMMSXSSXSAASXSMXAMAAMXSAMAAMASXXMXMAAXXXXSMSSSMASMMXAAMSSSXMXSSSSMXMAAMASAMXAXXMMMMAXAMMAAMAMAMXMAXAXAAASMSMSS',
    'MSMSMASASAAXSAMXMXSASASXSMSMSAAMAMXXAAMMMXMAMMAMSMSXSXMXSMASAMXMMSMMMAMXAXMAXASXSSMMXAMMAMXXAAMAXSAMSASASXMMXXXSAMMMAAXMSMMXSMMSSMSSSXSAAAAX',
    'XMAXMASMMASMSXMXMXMAMXMASAAASMSMASMMMMMSSSMAMMAMAXXMMASAXMMMMXSAAAXAXSAMMMSAMXMAMXMMMMSXMMAMMMMSMMAMMASXMAMXAAXAXMAXXMMXAXXMXAAAAXAAXAMMMMMS',
    'XMXMMMSXMAMAMXMMSAMAMXMXMMMXMAMXMXAAAMAAAXMMSSMSXSMMSAMXSMXXAAMSSXSASXMASAXXMXMMMXAXAAXASXXSAMMAAMSXMMMMMAMMMMMMMXXMASXXMSSXSMMSMMMSMSMXXAMX',
    'SXMXMAMMSASAMXMASASXSASASASAMXXAMSMMMSMMSMXAAAXMAAMAMASXMASMMMXMXMAXMXXXSASMSSSSMSMSMMSAMAXMASMSXMMMMMMSMMXXAAAXAASMMSAASAMMAMXXMAXAAXAXSXSX',
    'XXMAMASASASXXXMXMAMASASASXSXSMSAXAAXMXXXAMMMXMMMXMMXSSMXXMAXMMAXMASMMSMMMAMAAAAAAAXXAAMMMMMSXMAMXAMMSAXMASXSMSMSAXMAXMMMMASXSMASMXMMSMMASAMM',
    'MASASXSAMAMASXMSXXMMMXMAMAXAAASMSMSMAAXSASXSXSASAAMXXMASMSMXSSSSMSXMAAMAMAMMMMMMSMSMXMSXSAMXMMAMSSMASXMSAMAAAAXXMASXMSSXMXMAAMXMXXSXMASAMASX',
    'MMMAMMXAMSMMMAAXAMXXMXMAMXMSMAMXXXMMMMAXAMXSAAASMSMSSMAMAAASMAMMXXXMSSSSSSMXSAMXAAAMMMSAXXMAXSXMAMMMXAMXAMSMMMXSXMMAMXAXXXSXMASXMXMASXMXSAMX',
    'MASXSMSAMXAASMMMSMSASAXXXMAAMMSAMXMXXSMSMSAMXMXMXXMXMXAMSMMMMAMMASAXXAXAAAXASMSAMSMSSMMAMSSSMASAMXMSMSXMAMXMASMMAXMAMMMMMMAAXAMAAMSAMXXXMAMA',
    'MMSAAAAXXSSMMAMXXASAXXXSMXSXSAXMAXAAXXXAAMMSAXAMMSSMSSXMXMXSSMSMASXMMMMMMMMMSAAMMMXXAAMXMXAAAMXSXMASMAXMXSXSASASXMSAMAAAASXSMXSASXMASMXXSAMM',
    'MXMXMMMMAMAXXAMMMAMAMSSMAAMSMMSSSMSSSSMMXMASMSMSAAASAMXAXMAMAMXMXSASASAXXXXAMXMMSXMSSMMXAMSMMXMMXXASXMMXAXMMXSAMXAMAXSSSXSAXAMXXMASXAXSMSASX',
    'SMMSXSAXXSAMSXMAMMMSMXAMSMSAXAAXAAMAAXXAXMAMAMXMMMMMMMXSAMASAMXSMSASXSXSAMMSSMXASAMAAAMXMAAXMASMAMSMAXAMSSMMMMMMSMMSMMAMAMAMAMSASAMSXAMAXXMM',
    'AASMASXMMMAMAMSSMSAMMSSMMXMMMMSSMMMMMMXMMSAXSMSSMSSMXSAMMSAXAXXSAMXMAMAMAXAAAAMXSAMMSMMAMMMSMAAXASASXMMMAAXMAAAAXXAXAMXMXMASAMXAXMASMSMMMAXA',
    'MSAMXMAMXSAMAXAAAMXSAAAMMAXXXAAMAMXSASAMAMMMXAAAAAAMAMAMXMMXSMMMAMSSSMASAMMSSMMXSXMAAASMXMAAMXMSXSASXSXMMSMSSXMMXMMMAMSSXSXSASMSMXAXMMAMSMMM',
    'XXXMAXAMXSXSSMSAMMMMMMSASASXMMSSMSASMSAMSAMAMMMMMMSMSSMMSXXAMASXSMXAASAMXSXAMAMXMMSSMMXAXAXXSAXMAMAMASMSAAAMMASMMSMSAMAXASASXMAAAMASXMXMAAAX',
    'AXAXXSXSXXAXAAMMAXAXAXXAXXAMAXXXAMASASAMXAMXSXMASXXAMAXSAMMMSAMXAAMSMMMSMXMSXSMMSAXAMMMMMMXAMXMXSMMMAMAAMMMMSAMAAAASAMXSAMAMAMSMXAXAXMASXSSS',
    'MSSXMAMSMMXMMMMXSSMSASMSMSMAXSXMMMMMAMMMSXMMMMXASMMAMAMSAMAMMAMSXMMMMAAAAMMMAAAXMMMMMAAAXXASXMSXMAXMMSSMXMAXMXMMMSXMXXXMXSXMMXAAXSMXMSAXAAAA',
    'MAXAAMASASMAMAMXMAMXAMAAAMXSXAAMXAAMSMMAMASMXSMMSASXMAXMAMXMXAMMAMXXSMSSSXAMSMMMMMSSSMSMXAXXAASXSAMSMMAXXMMSASMXMXXAXMXMASAXXSXSMMAMAAXSMMMM',
    'MSSMMSXSMMASASMMSAMMMMSMSMAXAMMMSXMMXMMAXAMMAXAMSAMMXMSSXMAMXAAXAMMXXXAMAMMMAXXAMXAAAMAXAXMMMMMAMXXAAXMMMSMMASXAMMSXMMAMXXAMXAMMAXMAXAXAXAXM',
    'MAAAASASXSSMMXAMSAMAAMAAAMMMMSSXMMSMAXMSXSAMXMAMMMMSSMAAAMASXSMSASXSMMMMAXXMXSSSXMMMMMAASAMXAAMXSSSSSMSAXAAMSMMMSASAMSMSMMSMMSXSAMMMSAMXXMAS',
    'MSSMMMAMAMXMXSAMXSSSMSMSXMSAAAXAMAAMASXAAMXSAMXXXAAXAMXSXMASXAMSMSAMAAAMSMMSAMAXXMSXMMSXMMAMSXSAXAAAMMMSSMSMXAXXAMXAMAXMAAAAXAAXASXAAAXAMXAM',
    'XMAMSMMMSMMSAMAMAXXXXAAMAASMMMSXMSSMAMMMMMAAAXAMSMSSXMMMXXMSXMXXXMAMMMMMAAXSAMAMSAXMMAMAMXAAAAMXMMMMMXMAMXXAMXMMMSSMMSSXMASXMMXSSMMMXSMXXASX',
    'MMAMAAAAMSAMXSSMMSMSSMMMMMXXXMXMMXXMAXAXAMXMMMSXMAAXAAAMMMMMMSMMMSAMSMSSMSMSMMXMXXMSXAMAMSMSMXMMSASAXMMXSASAAASMMAAAAAMMXMMAAXAMXAXAXMAXAAXS',
    'MMMSMMMXXAMXAAXAXAMMXXAXXSMSMSASXMXXASMSSSMXAAXASMSSMMMXAASAXAXAMMASXAXXXAAMXSXSMMASMMMAXXAAMAMXSAXASXAAMMSXSMMAMSSMMMSAASMSMMSSSMMXMMAMSXMX',
    'MAMAXSSMMSSMAMXAMMMSAASMXAAAASAMASAXXXMAXAAMMMSAMAMMAAXMSMSAMMSXXAXMMXMASMSMAMAAAMAMAMSMMMXMSSSMMSMAMMMMSXSAMXSAMAAAAXMXSAAMAAMXAXSAMMMMXAMX',
    'SXSAXMAMXAAMMMASXSAMXMMAXMSMMMMMXMMMMAMXSSSSSXMMMSMSMSSXMAXAMXAMSSMXXXAMXAAMAMSMXMASMMASXASMXAAMAMXSMXMXSAMAMASASXSMMMAMMMMMMSMSMMSXMAXSMSMS',
    'XMMMMSMMMSSMXMXXAMASMSASXXMMSMMMAMAAXAMXAAAAXAMXAXXXAAMMMMMSMXAXAMAXSMXMXSMXAMAXMSASMSAXXMAXAXMMXSAMXXXAMAMXMXSMMMMMMSSMASXMXMAMXAMASMMSAAAX',
    'XAAAXAXXAXAMMMAMAMXMASAMSXSAAAASAMMMXAMXMMMMMMMMMMMMMMSAMAAXMXMMMMSAAXAMXXXMSSMSAMASAMXXSASMSSSXAMMMMMMSSMMSMXSXSXAXMAAMASAMAMAMMAMMMXAMSMMM',
    'MSSSSSMMMSXMAMASAMAMMMAMSMMXMSMXASASXMMAXXAXSMASMASAMASASMSSMXSAXSMMMSASMSSMAAAAMMAMMMSAMAXAXAXMXSAAAXAAXAASMMSAMSMSMSSMXSAMASAMSMXSAMMMXXXA',
    'AAAMAXXAXAAMXSMMASXSAMAMXASXMMXSAMASXSMSSMXSAMAXXAMAMAXMMXMAAASAMXAAXSXAXAAXMMMMMMSSMAMASAMSMMMSXSMSSMMSSMMSAAMXMAXMXAAXASASASAMSAASAMSAMXXA',
    'SMSMAMSSMMMSMAMSMMASXSSSSSMAAAXMXMMMMAXMMXMAMMASXMSAMMSMSXSMMMSASXSMASXMMSMMXAXSAXXAMXSAMXSXMSAAMXAXMAAAAXASMMSMSMSSMMMMMSAMASMMMMMSAMMMSMSX',
    'AAMMSXXXAXAAXAMAASMSXAAAMMSXMMSMAXAAXMMXAAXAXXAMXAXASXAASXSXSXSAMAAMAMAXAXXAXXMSMXSAMXMXSMMAAMXXAMSMSMMSAMXSXXMAXMAMAXXAXMAMMMXSSMAMAMXMAMMM',
    'MMMAMMSSMMSSSMSMXMAXMMMXMASMSAAMASXXMXAMMMXXSMASMMSMMMMMMASXMAMXMSXMASMMMXSSSMASAMMXMXXXXAXAMMMMSAAASXMMMSAXMMSXXMASMSSMMSSMXMXAAMXSAMXMAXAM',
    'XMMAMXAAAAXAAAAXSMSMXXXXMASAMXSMMXMAMXMAXXAMXMAXAXAXSXSAMMMAMSMSMMXMAXMASAAXMAXSAMXAMSMMMSSMMSAAMSMXMAXXAMMMSAAMSXMXAXXAASAMXAMSSMXSASXSMSAS',
    'SXMMSMSSMMMSMMMSXAXMAMASMAMAMMXASXXSAMXSASMMMAXSSSSXSAXMMASAMAMAAXAMMMSAMMSMSSMMXMSXXAAAAMAAAMSMMMXMSSMMMXSAMSSSMASMSMMMXXAMMXMAXMXSMMMAMSAM',
    'XAMAXAMXAMXMMXXXMMMMAMXAMASAMASXMAAXAMAMAXMASMMMAAXAMSMXSASASXSSSMSXSAMXSAXMAMXXSMSMSXSMSMMMMXAXMXAMAAAXAAMMMAMAMAMAAAAXASMXMAMMASAMXAMAMMMM',
    'SSMSSSMSSSSMSSMAMMAMAMXMSMSASMMAMMMMMMXSMSAMXXAMMMMAMMMXMASAMMMAXAAAMXMSMMSMMSSXXAXAAXXXMXMAMXXMASMMSSMMMSSXMXSSMSSSSSMSMXAAMMSSMSASMXSMSAMX',
    'XXAAAXXXXAMSAXMAMMMSASMXAAXAMXSAMAAAAMXXAMXAMMSMXXAMSASXSXMXMAMAMSMMMSXMAXAXMAMAMMMMMXMAMAMAMSSMMSAMXMASAAMMMMXXAXAAAMAMXSSSMXAAMSAMMASASASM',
    'AMMMSMMMXMMMSSMMSAASAMXSMSMMMMMASMSSXSASXMSASMAMASMMSASAMAMAMXMMXMAXAXASMMSMMXSMSAAAAAMAMSSMMAAMXSXMAMSMMXSAAASMSMMMMMAMXAAMXMSSMMMMMAMXSAMM',
    'SXMAXAXMASMXAXAAXMASAMASAMXAAMSMMMAMXMASAAMAXXAMAAAAMXMASASASAXMASMMSSMMAAXAMAMXMASMSMMAMMAMMSMMASMSMSAAMXSXSMSAAMASASXSAMMSXXAAXAAAMXSXMAMX',
    'MAMAXXMXAXAMMSMMSXMSAMMXXXXSXXAMAMAMXMASXMMSMSMSMSMMMXXASMMASMMSASAAAXXXMMSXMASASXMMXMSMSMAMXMAMASMXSSXSMAMAMAMMMSASAMSAXXAXAMMSMSSMSMSASAMX',
    'SAMMSMSMSSXMXSAXMAMXXAXSMSMASMXSASXSXMXMASAXAXAXAXASMSSMMAMXMMAMSSMMMSSSXMAMSASXXAMXAXAAXMSMMXSMAMASXMAMMAMAMAMAXMAMAXAMMMMSMAMAAXAMAMXAMMSS',
    'SASXAAXAAXAMXSXMSMMMSMAAAAMXMXMSMSAMXASMMMSSXMXMAXXAAAXAMMMSAMXSXSASMXMASMXMMASAMSMSSSMXMMMASAXMXSMMAMAMSASAMXSMMSSMMMMXAAMMMMAMXXMMSSMSMSAX',
    'MMMXMSMMMSMMAMAAXXAAAMSMSMSMMSMSAMAMMMXAXAXMXSAMXSSMMMSMMSXMAMXMASMMMAMAMMMMMAMAMXAXMAMASASAMXMMAAXSSMAMSXSASAAXAAAAXAXSSXSAAMXSSMSAASAMXMMS',
    'SAAXSXAXAAAAXMMMAMSSMMAAAMAAMXAMXSAMXXSAMXSAAXXXMAXXAXAXAXAAXMAMAMAAMAMMMSAMMXSSMMXMMAMAAAMSMAMXAMMXXXXMMAMAAXXMMSSMMSMMMAMXMSAXAAMMMMMMXAAM',
    'SMASXSMMSSSMSXSMSMXAXSMSMSSSMMXMASASMASAMAXMASMMSMMSSSMMSSXMASAMASXMSSSMAMSASMMAAMMSSSSXMAMAMMMSAMAMMMMAMAMMMASAMAXAAAAAMMMSXMASMSMMASAMSMSS',
    'SAMXXXXAAMAMMAXAXMASMXXAAMXMASXMXSAMMAMAMMSAMSAASAAAXAXAMSASASASMSAAAAAMXSMMMASMMSAAMXMXXSSMSAASAMSXMASASASAXMASMMSMMSSMSXXSAMXXXAXSASAMMAAM',
    'SSXMASMMSSMMMAMMMASAMXSMSMASAMAXAMAMMSSXMXXXMSXMSMMXSAMSSSXMMSAMXSMMMSMMSMMXAXXXSMMXSAXSAMXXMMXSSMASMXSMSMSASMXXMXXXAXMASAXSXMSASAMMXSXMMMMS',
]

type grid = Array<Array<string>>

export class WordSearch {
    grids: {
        leftRight: grid,
        rightLeft: grid,
        topBottom: grid,
        bottomTop: grid,
        upRight: grid,
        downRight: grid,
        downLeft: grid,
        upLeft: grid,
    };
    fullString: any;
    count: number = 0;
    constructor (input: Array<string>) {
        const baseGrid = input.map(ele => ele.split(''));
        this.grids = {
            leftRight: baseGrid,
            rightLeft: baseGrid.map(ele => ele.toReversed()),
            topBottom: topBottom(baseGrid),
            bottomTop: topBottom(baseGrid).map(ele => ele.reverse()),
            upRight: upRight(baseGrid),
            downRight: downRight(baseGrid),
            downLeft: upRight(baseGrid).map(ele => ele.reverse()),
            upLeft: downRight(baseGrid).map(ele => ele.reverse())
        }
        this.fullString = Object.values(this.grids).map(ele => {
            return {
                string: ele.map(ele => ele.join().replace(/,/g,'')).join(),
                count: 0
            }
        })
        this.fullString.forEach((ele: any) => {
            const length = ele.string.match(/XMAS/g)?.length;
            ele.count += length;
            this.count += length || 0;
        })
    }
}

function topBottom (grid: Array<Array<string>>) {
    const newGrid: grid = [];
    for (let i = 0; i < grid[0].length; i ++) {
        const newRow: Array<string> = [];
        for(let ii = 0; ii < grid.length; ii ++) {
            newRow.push(grid[ii][i])
        }
        newGrid.push(newRow)
    }
    return newGrid
}

function upRight (grid: Array<Array<string>>) {
    const newGrid: grid = [];
    for (let i = 0; i < grid[0].length + grid.length - 1; i ++) {
        const newRow: Array<string> = [];
        let y = i < grid.length ? i : grid.length - 1;
        let x = i < grid[y].length ? 0 : i - grid[y].length + 1;
        while (y >= 0 && x < grid[y].length) {
            newRow.push(grid[y][x])
            x ++;
            y --;
        }
        // console.log(newRow)
        newGrid.push(newRow)
    }
    return newGrid
}

function downRight (grid: Array<Array<string>>) {
    const newGrid: grid = [];
    for (let i = 0; i < grid.length + grid[0].length - 1; i ++) {
        const newRow: Array<string> = [];
        let y = i < grid.length ? 0 : i - grid.length + 1;
        // console.log('grid[y]: ', grid[y])
        let x = i < grid[y].length ? grid[y].length - 1 - i : 0;
        // console.log({x, y})
        while (y < grid.length && x < grid[y].length) {
            newRow.push(grid[y][x])
            x ++;
            y ++;
        }
        newGrid.push(newRow)
    }
    return newGrid
}

// downRight length = 3x3
// i=0: 2,0
// i=1: 1,0; 2,1
// i=2: 0,0; 1,1; 2,2
// i=3: 0,1; 1,2
// i=4: 0,2
// y never exceeds x
// push a new line every time y = i
// if i < grid.length, y = 0; else y = i - grid.length
// if i < grid[y].length, x = grid[y].length - i - 1; else x = 0